[2025-04-11T08:37:43.080+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_email_every_2hrs.query_postgres scheduled__2025-04-11T06:00:00+00:00 [queued]>
[2025-04-11T08:37:43.089+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_email_every_2hrs.query_postgres scheduled__2025-04-11T06:00:00+00:00 [queued]>
[2025-04-11T08:37:43.089+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-11T08:37:43.104+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): query_postgres> on 2025-04-11 06:00:00+00:00
[2025-04-11T08:37:43.112+0000] {standard_task_runner.py:60} INFO - Started process 200 to run task
[2025-04-11T08:37:43.116+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'query_email_every_2hrs', 'query_postgres', 'scheduled__2025-04-11T06:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/query_email_dag.py', '--cfg-path', '/tmp/tmpc8rn7nnr']
[2025-04-11T08:37:43.120+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask query_postgres
[2025-04-11T08:37:43.140+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-11T08:37:43.186+0000] {task_command.py:423} INFO - Running <TaskInstance: query_email_every_2hrs.query_postgres scheduled__2025-04-11T06:00:00+00:00 [running]> on host 7a9df312bb09
[2025-04-11T08:37:43.266+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='query_email_every_2hrs' AIRFLOW_CTX_TASK_ID='query_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-11T06:00:00+00:00'
[2025-04-11T08:37:43.284+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/query_email_dag.py", line 24, in get_postgres_data
    results = hook.get_records(sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 261, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 128, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_postgres_conn` isn't defined
[2025-04-11T08:37:43.292+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=query_email_every_2hrs, task_id=query_postgres, execution_date=20250411T060000, start_date=20250411T083743, end_date=20250411T083743
[2025-04-11T08:37:43.303+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task query_postgres (The conn_id `my_postgres_conn` isn't defined; 200)
[2025-04-11T08:37:43.332+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-11T08:37:43.354+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
